// report.ts — Generate a written "gazetteer" for a world.
//
// Turns a World into a self-contained Markdown dossier: an overview, the notable
// features, a table of regions, the settlement hierarchy, and the full
// chronicle. It's the narrative counterpart to the maps — proof that all the
// layers cohere into one place with a name and a story.

import type { World } from "./world.ts";
import { BIOME_NAMES, type Biome } from "./biomes.ts";

function pct(x: number): string {
  return `${(x * 100).toFixed(1)}%`;
}

function titleForWorld(world: World): string {
  // Prefer the largest realm's name; fall back to the capital or seed.
  const realm = world.history.realms
    .slice()
    .sort((a, b) => a.foundedYear - b.foundedYear)[0];
  return realm ? realm.name : world.meta.capital;
}

export function worldReportMarkdown(world: World): string {
  const m = world.meta;
  const h = world.history;
  const worldName = titleForWorld(world);
  const lines: string[] = [];

  lines.push(`# ${worldName}`);
  lines.push("");
  lines.push(
    `*A world generated by Cartogenesis v${m.engineVersion} from seed \`${m.seed}\`.` +
      ` Regenerate it exactly with \`node src/cli.ts generate --seed ${m.seed}\`.*`,
  );
  lines.push("");

  // Overview
  lines.push("## Overview");
  lines.push("");
  lines.push(`- **Extent:** ${m.width} × ${m.height} cells`);
  lines.push(
    `- **Land / ocean:** ${pct(m.landFraction)} land, ${pct(m.oceanFraction)} ocean` +
      `, ${m.lakeCount} lake(s)`,
  );
  lines.push(
    `- **Climate & life:** dominant biome **${m.dominantBiome}**, ${m.biomeDiversity} biomes in all`,
  );
  lines.push(
    `- **Peoples:** ${m.regionCount} regions, ${m.settlementCount} settlements, ` +
      `${m.realmCount} realms`,
  );
  lines.push(`- **Capital:** ${m.capital}`);
  lines.push(`- **The present year:** ${h.presentYear} ${h.epoch}`);
  lines.push("");

  // Notable features
  if (h.features.length) {
    lines.push("## Notable features");
    lines.push("");
    for (const f of h.features) {
      const label =
        f.kind === "peak"
          ? `**Mount ${f.name}** — the highest peak`
          : f.kind === "river"
            ? `**The ${f.name}** — the greatest river`
            : `**Lake ${f.name}** — the largest inland water`;
      lines.push(`- ${label}`);
    }
    lines.push("");
  }

  // Regions table
  lines.push("## Regions");
  lines.push("");
  lines.push("| Region | Culture | Area | Dominant biome | Coast |");
  lines.push("|--------|---------|-----:|----------------|:-----:|");
  const regions = [...world.regions.regions].sort((a, b) => b.area - a.area);
  for (const r of regions) {
    lines.push(
      `| ${r.name} | ${r.languageLabel} | ${r.area} | ` +
        `${BIOME_NAMES[r.dominantBiome as Biome]} | ${r.coastal ? "yes" : "—"} |`,
    );
  }
  lines.push("");

  // Settlements
  lines.push("## Settlements");
  lines.push("");
  const tiers: Array<["city" | "town" | "village", string]> = [
    ["city", "Cities"],
    ["town", "Towns"],
    ["village", "Villages"],
  ];
  for (const [tier, heading] of tiers) {
    const list = world.settlements.settlements.filter((s) => s.tier === tier);
    if (!list.length) continue;
    lines.push(`### ${heading}`);
    lines.push("");
    for (const s of list) {
      const tags = [
        s.isCapital ? "**capital**" : "",
        s.isPort ? "port" : "",
      ]
        .filter(Boolean)
        .join(", ");
      lines.push(`- ${s.name}${tags ? ` (${tags})` : ""}`);
    }
    lines.push("");
  }

  // Chronicle
  lines.push("## Chronicle");
  lines.push("");
  for (const e of h.events) {
    lines.push(`- **${e.year} ${h.epoch}** — ${e.text}`);
  }
  lines.push("");

  lines.push("---");
  lines.push("");
  lines.push(
    `*Elevation fingerprint \`${m.contentHash}\`. This document and every map of ` +
      `${worldName} are pure functions of the seed — reproducible anywhere, forever.*`,
  );
  lines.push("");

  return lines.join("\n");
}
