// report.ts — Generate a written "gazetteer" for a world.
//
// Turns a World into a self-contained Markdown dossier: an overview, the notable
// features, a table of regions, the settlement hierarchy, and the full
// chronicle. It's the narrative counterpart to the maps — proof that all the
// layers cohere into one place with a name and a story.

import { type World, elevationToMetres } from "./world.ts";
import { BIOME_NAMES, Biome } from "./biomes.ts";
import { RESOURCE_NAMES } from "./resources.ts";
import { glossPhrase, glossary } from "./language.ts";
import { languageById } from "./names.ts";

function pct(x: number): string {
  return `${(x * 100).toFixed(1)}%`;
}

function titleForWorld(world: World): string {
  // Prefer the largest realm's name; fall back to the capital or seed.
  const realm = world.history.realms
    .slice()
    .sort((a, b) => a.foundedYear - b.foundedYear)[0];
  return realm ? realm.name : world.meta.capital;
}

export function worldReportMarkdown(world: World): string {
  const m = world.meta;
  const h = world.history;
  const worldName = titleForWorld(world);
  const lines: string[] = [];

  lines.push(`# ${worldName}`);
  lines.push("");
  lines.push(
    `*A world generated by Cartogenesis v${m.engineVersion} from seed \`${m.seed}\`.` +
      ` Regenerate it exactly with \`node src/cli.ts generate --seed ${m.seed}\`.*`,
  );
  lines.push("");

  // Overview
  lines.push("## Overview");
  lines.push("");
  lines.push(`- **Extent:** ${m.width} × ${m.height} cells`);
  lines.push(
    `- **Land / ocean:** ${pct(m.landFraction)} land, ${pct(m.oceanFraction)} ocean` +
      `, ${m.lakeCount} lake(s)`,
  );
  lines.push(
    `- **Climate & life:** dominant biome **${m.dominantBiome}**, ${m.biomeDiversity} biomes in all`,
  );
  lines.push(
    `- **Peoples:** ${m.regionCount} regions, ${m.settlementCount} settlements, ` +
      `${m.realmCount} realms`,
  );
  lines.push(`- **Capital:** ${m.capital}, seat of House ${m.capitalHouse}`);
  lines.push(
    `- **Dominant power:** ${m.dominantPower} (of ${m.survivingRealms} surviving realm(s))`,
  );
  lines.push(`- **The present year:** ${m.presentYear} ${h.epoch}`);
  lines.push(
    `- **Highest peak:** ${m.highestPeakMetres.toLocaleString()} m · ` +
      `**volcanoes:** ${m.volcanoCount} (${m.activeVolcanoes} active)`,
  );
  lines.push("");

  // Volcanoes
  if (world.volcanoes.length) {
    lines.push("## Volcanoes");
    lines.push("");
    const vs = [...world.volcanoes].sort((a, b) => b.summit - a.summit);
    for (const v of vs) {
      const metres = elevationToMetres(v.summit, m.seaLevel, m.maxAltitudeMetres);
      const form = v.caldera
        ? v.caldera.lakeLevel !== undefined
          ? ", **caldera** cradling a crater lake"
          : ", a collapsed **caldera**"
        : "";
      const arc = v.arcId !== undefined ? ", one of an island arc" : "";
      lines.push(
        `- **Mount ${v.name}** — *${glossPhrase(v.gloss)}* — ${v.type}, ${v.status}, ` +
          `summit ${metres.toLocaleString()} m${form}${arc}`,
      );
    }
    const arcCount = new Set(
      world.volcanoes.filter((v) => v.arcId !== undefined).map((v) => v.arcId),
    ).size;
    if (arcCount > 0) {
      lines.push("");
      lines.push(
        `*${arcCount} of the volcanic system${arcCount > 1 ? "s form island arcs" : " forms an island arc"}` +
          ` — chains of cones strung along a line, as they rise over a moving plate.*`,
      );
    }
    const lavaCells = world.biomes.counts[Biome.LavaField] ?? 0;
    if (lavaCells > 0) {
      lines.push("");
      lines.push(
        `*Fresh lava fields streak the flanks of the living peaks — ${lavaCells} ` +
          `cells of cooled basalt where nothing grows and no one builds.*`,
      );
    }
    lines.push("");
  }

  // Notable features
  if (h.features.length) {
    lines.push("## Notable features");
    lines.push("");
    for (const f of h.features) {
      const label =
        f.kind === "peak"
          ? `**Mount ${f.name}** — the highest peak`
          : f.kind === "river"
            ? `**The ${f.name}** — the greatest river`
            : `**Lake ${f.name}** — the largest inland water`;
      lines.push(`- ${label}, *${glossPhrase(f.gloss)}*`);
    }
    lines.push("");
  }

  // Regions table
  lines.push("## Regions");
  lines.push("");
  lines.push("| Region | Meaning | Culture | Area | Dominant biome | Coast |");
  lines.push("|--------|---------|---------|-----:|----------------|:-----:|");
  const regions = [...world.regions.regions].sort((a, b) => b.area - a.area);
  for (const r of regions) {
    lines.push(
      `| ${r.name} | *${glossPhrase(r.gloss)}* | ${r.languageLabel} | ${r.area} | ` +
        `${BIOME_NAMES[r.dominantBiome as Biome]} | ${r.coastal ? "yes" : "—"} |`,
    );
  }
  lines.push("");

  // Region descriptions (prose), skipping tiny islets.
  const described = regions.filter((r) => r.area >= 30);
  if (described.length) {
    for (const r of described) {
      lines.push(`- ${world.lore.regionDescriptions[r.id]}`);
    }
    lines.push("");
  }

  // Ruling houses & rulers
  if (world.lore.houses.length) {
    lines.push("## Ruling houses");
    lines.push("");
    const realmsByFounding = [...world.history.realms].sort(
      (a, b) => a.foundedYear - b.foundedYear,
    );
    for (const realm of realmsByFounding) {
      const house = world.lore.houses.find((x) => x.realmId === realm.id);
      if (!house) continue;
      lines.push(
        `### House ${house.name} — realm of ${realm.name}`,
      );
      lines.push("");
      lines.push(
        `*${house.name}, ${glossPhrase(house.gloss)}; ${realm.name}, ` +
          `${glossPhrase(realm.gloss)}.*`,
      );
      lines.push("");
      const line = world.lore.rulers
        .filter((x) => x.realmId === realm.id)
        .sort((a, b) => a.startYear - b.startYear);
      const entry = (r: (typeof line)[number]) =>
        `- **${r.startYear}–${r.endYear}** ${r.name}${r.reigning ? " *(reigning)*" : ""}`;
      // A thousand-year dynasty is a long king-list; show the ends of it.
      if (line.length > 10) {
        for (const r of line.slice(0, 4)) lines.push(entry(r));
        lines.push(`- *… ${line.length - 8} rulers over the intervening years …*`);
        for (const r of line.slice(-4)) lines.push(entry(r));
      } else {
        for (const r of line) lines.push(entry(r));
      }
      lines.push("");
    }
  }

  // Notable figures
  if (world.lore.figures.length) {
    lines.push("## Notable figures");
    lines.push("");
    for (const f of world.lore.figures) {
      lines.push(`- **${f.name}** — ${f.description}`);
    }
    lines.push("");
  }

  // Settlements
  lines.push("## Settlements");
  lines.push("");
  const tiers: Array<["city" | "town" | "village", string]> = [
    ["city", "Cities"],
    ["town", "Towns"],
    ["village", "Villages"],
  ];
  const timeline = new Map(
    world.simulation.settlementTimeline.map((t) => [t.id, t]),
  );
  const standing = world.settlements.settlements.filter(
    (s) => timeline.get(s.id)?.fellYear === undefined,
  );
  for (const [tier, heading] of tiers) {
    const list = standing.filter((s) => s.tier === tier);
    if (!list.length) continue;
    lines.push(`### ${heading}`);
    lines.push("");
    for (const s of list) {
      const eco = world.economy.economies.find((e) => e.settlementId === s.id);
      const tags = [
        s.isCapital ? "**capital**" : "",
        s.isPort ? "port" : "",
        eco?.isTradeHub ? "trade hub" : "",
        eco ? eco.tier : "",
      ]
        .filter(Boolean)
        .join(", ");
      const goods = eco && eco.produces.length
        ? ` — ${eco.produces.map((k) => RESOURCE_NAMES[k]).join(", ")}`
        : "";
      const founded = timeline.get(s.id)?.foundedYear;
      const age = founded !== undefined ? ` *(founded ${founded})*` : "";
      const former = s.formerNames?.length
        ? ` — formerly **${s.formerNames[0].name}**, before conquest remade the name`
        : "";
      lines.push(
        `- **${s.name}**, *${glossPhrase(s.gloss)}*` +
          `${tags ? ` (${tags})` : ""}${goods}${age}${former}`,
      );
    }
    lines.push("");
  }

  // Ruins — the settlements history swallowed.
  const ruins = world.simulation.settlementTimeline
    .filter((t) => t.fellYear !== undefined)
    .sort((a, b) => (a.fellYear ?? 0) - (b.fellYear ?? 0));
  if (ruins.length) {
    lines.push("## Ruins");
    lines.push("");
    lines.push("*Settlements that did not survive to the present day.*");
    lines.push("");
    for (const r of ruins) {
      const how = r.fate === "sacked" ? "stormed and left a ruin" : "abandoned";
      lines.push(
        `- **${r.name}** (${r.tier}) — founded ${r.foundedYear}, ${how} in ${r.fellYear}`,
      );
    }
    lines.push("");
  }

  // Names remade by conquest — where a foreign power ruled long enough to leave
  // its tongue on the map.
  const remade = [...world.simulation.renamings].sort((a, b) => a.year - b.year);
  if (remade.length) {
    lines.push("## Names remade by conquest");
    lines.push("");
    lines.push(
      "*Where a foreign power held a land long enough, its towns took new names — " +
        "the old land-word kept, the settlement re-said in the ruler's tongue.*",
    );
    lines.push("");
    for (const r of remade) {
      lines.push(
        `- **${r.formerName}** → **${r.name}** *(${glossPhrase(r.gloss)})* — ` +
          `${r.fromCulture} land under ${r.toCulture} rule, c. ${r.year}`,
      );
    }
    lines.push("");
  }

  // Faiths
  if (world.religion.faiths.length) {
    lines.push("## Faiths");
    lines.push("");
    for (const f of world.religion.faiths) {
      lines.push(
        `### ${f.name} — ${f.deity.name}, god of ${f.deity.domain}`,
      );
      lines.push("");
      lines.push(
        `*${f.deity.name}: ${glossPhrase(f.deity.gloss)}.*`,
      );
      lines.push("");
      lines.push(`> ${f.myth}`);
      lines.push("");
      lines.push(`Followed across ${f.followerRegions.length} region(s).`);
      lines.push("");
    }
  }

  // Resources & trade
  lines.push("## Resources & trade");
  lines.push("");
  if (m.majorExports) lines.push(`- **Major exports:** ${m.majorExports}`);
  const richestTown = world.settlements.settlements.find(
    (s) => s.id === world.economy.richest,
  );
  if (richestTown) lines.push(`- **Wealthiest settlement:** ${richestTown.name}`);
  const hubs = world.economy.economies
    .filter((e) => e.isTradeHub)
    .map((e) => world.settlements.settlements.find((s) => s.id === e.settlementId)?.name)
    .filter(Boolean);
  if (hubs.length) lines.push(`- **Trade hubs:** ${hubs.join(", ")}`);
  const depCounts = Object.entries(world.resources.counts)
    .filter(([, c]) => (c as number) > 0)
    .map(([k, c]) => `${RESOURCE_NAMES[Number(k)]} ×${c}`);
  if (depCounts.length) lines.push(`- **Deposits:** ${depCounts.join(", ")}`);
  lines.push("");

  // Languages — the vocabulary behind every name above. Only the cultures that
  // actually live here; an unspoken glossary is noise.
  const spoken = [...new Set(world.regions.regions.map((r) => r.languageId))];
  if (spoken.length) {
    lines.push("## Languages");
    lines.push("");
    lines.push(
      "*Every place-name in this world is a compound of the roots below. " +
        "Read them and the map reads back.*",
    );
    lines.push("");
    for (const id of spoken) {
      const lang = languageById(id);
      const spokenIn = world.regions.regions
        .filter((r) => r.languageId === id)
        .sort((a, b) => b.area - a.area)
        .slice(0, 3)
        .map((r) => r.name);
      lines.push(`### ${lang.label}`);
      lines.push("");
      lines.push(`*Spoken in ${spokenIn.join(", ")}.*`);
      lines.push("");
      lines.push(
        glossary(lang)
          .map((g) => `**${g.root}** ${g.gloss}`)
          .join(" · "),
      );
      lines.push("");
    }
  }

  // Legends of the founding age (the static, mythic prehistory).
  lines.push("## Legends of the founding age");
  lines.push("");
  for (const e of h.events) {
    lines.push(`- **${e.year} ${h.epoch}** — ${e.text}`);
  }
  lines.push("");

  // Rise and fall of realms (from the simulation).
  const sim = world.simulation;
  const notable = [...sim.realms]
    .filter((r) => r.peakSize >= 2 || r.status !== "extinct")
    .sort((a, b) => b.peakSize - a.peakSize || a.foundedYear - b.foundedYear);
  if (notable.length) {
    lines.push("## Rise and fall of realms");
    lines.push("");
    lines.push(
      `*Simulated ${sim.startYear}–${sim.endYear} ${h.epoch}. ` +
        `${sim.survivingRealms} realm(s) endured to the present.*`,
    );
    lines.push("");
    lines.push("| Realm | Founded | Peak | Peak year | Final | Fate |");
    lines.push("|-------|--------:|-----:|----------:|------:|------|");
    for (const r of notable) {
      lines.push(
        `| ${r.name} | ${r.foundedYear} | ${r.peakSize} | ${r.peakYear} | ` +
          `${r.finalSize} | ${r.status} |`,
      );
    }
    lines.push("");
  }

  // The chronicle, told — L17's narrated history, in an in-world voice.
  const nar = world.narrative;
  lines.push(`## ${nar.title}`);
  lines.push("");
  for (const p of nar.opening) {
    lines.push(`*${p}*`);
    lines.push("");
  }
  for (const ch of nar.chapters) {
    lines.push(`### ${ch.title}`);
    lines.push("");
    for (const p of ch.paragraphs) {
      lines.push(p);
      lines.push("");
    }
  }
  for (const p of nar.closing) {
    lines.push(`*${p}*`);
    lines.push("");
  }

  // The raw dated record the chronicle above was told from.
  lines.push("## Annals");
  lines.push("");
  lines.push("*The ledger behind the chronicle: every event, dated, unadorned.*");
  lines.push("");
  for (const e of sim.events) {
    lines.push(`- **${e.year} ${h.epoch}** — ${e.text}`);
  }
  lines.push("");

  lines.push("## Heightmap");
  lines.push("");
  lines.push(
    `A real ${m.width}×${m.height} 16-bit heightmap is exported alongside this ` +
      `report (\`.heightmap16.png\` and raw \`.heightmap.r16\`). Import it into ` +
      `Blender, Unity, Godot, or World Machine and scale the height to ` +
      `**${m.maxAltitudeMetres.toLocaleString()} m** (value 65535 = ${m.maxAltitudeMetres.toLocaleString()} m ` +
      `above the lowest point). The topographic contour map (\`.topo.png\`) shows ` +
      `the same relief as isolines.`,
  );
  lines.push("");

  lines.push("---");
  lines.push("");
  lines.push(
    `*Elevation fingerprint \`${m.contentHash}\`. This document and every map of ` +
      `${worldName} are pure functions of the seed — reproducible anywhere, forever.*`,
  );
  lines.push("");

  return lines.join("\n");
}
