// report.ts — Generate a written "gazetteer" for a world.
//
// Turns a World into a self-contained Markdown dossier: an overview, the notable
// features, a table of regions, the settlement hierarchy, and the full
// chronicle. It's the narrative counterpart to the maps — proof that all the
// layers cohere into one place with a name and a story.

import type { World } from "./world.ts";
import { BIOME_NAMES, type Biome } from "./biomes.ts";
import { RESOURCE_NAMES } from "./resources.ts";

function pct(x: number): string {
  return `${(x * 100).toFixed(1)}%`;
}

function titleForWorld(world: World): string {
  // Prefer the largest realm's name; fall back to the capital or seed.
  const realm = world.history.realms
    .slice()
    .sort((a, b) => a.foundedYear - b.foundedYear)[0];
  return realm ? realm.name : world.meta.capital;
}

export function worldReportMarkdown(world: World): string {
  const m = world.meta;
  const h = world.history;
  const worldName = titleForWorld(world);
  const lines: string[] = [];

  lines.push(`# ${worldName}`);
  lines.push("");
  lines.push(
    `*A world generated by Cartogenesis v${m.engineVersion} from seed \`${m.seed}\`.` +
      ` Regenerate it exactly with \`node src/cli.ts generate --seed ${m.seed}\`.*`,
  );
  lines.push("");

  // Overview
  lines.push("## Overview");
  lines.push("");
  lines.push(`- **Extent:** ${m.width} × ${m.height} cells`);
  lines.push(
    `- **Land / ocean:** ${pct(m.landFraction)} land, ${pct(m.oceanFraction)} ocean` +
      `, ${m.lakeCount} lake(s)`,
  );
  lines.push(
    `- **Climate & life:** dominant biome **${m.dominantBiome}**, ${m.biomeDiversity} biomes in all`,
  );
  lines.push(
    `- **Peoples:** ${m.regionCount} regions, ${m.settlementCount} settlements, ` +
      `${m.realmCount} realms`,
  );
  lines.push(`- **Capital:** ${m.capital}, seat of House ${m.capitalHouse}`);
  lines.push(`- **The present year:** ${h.presentYear} ${h.epoch}`);
  lines.push("");

  // Notable features
  if (h.features.length) {
    lines.push("## Notable features");
    lines.push("");
    for (const f of h.features) {
      const label =
        f.kind === "peak"
          ? `**Mount ${f.name}** — the highest peak`
          : f.kind === "river"
            ? `**The ${f.name}** — the greatest river`
            : `**Lake ${f.name}** — the largest inland water`;
      lines.push(`- ${label}`);
    }
    lines.push("");
  }

  // Regions table
  lines.push("## Regions");
  lines.push("");
  lines.push("| Region | Culture | Area | Dominant biome | Coast |");
  lines.push("|--------|---------|-----:|----------------|:-----:|");
  const regions = [...world.regions.regions].sort((a, b) => b.area - a.area);
  for (const r of regions) {
    lines.push(
      `| ${r.name} | ${r.languageLabel} | ${r.area} | ` +
        `${BIOME_NAMES[r.dominantBiome as Biome]} | ${r.coastal ? "yes" : "—"} |`,
    );
  }
  lines.push("");

  // Region descriptions (prose), skipping tiny islets.
  const described = regions.filter((r) => r.area >= 30);
  if (described.length) {
    for (const r of described) {
      lines.push(`- ${world.lore.regionDescriptions[r.id]}`);
    }
    lines.push("");
  }

  // Ruling houses & rulers
  if (world.lore.houses.length) {
    lines.push("## Ruling houses");
    lines.push("");
    const realmsByFounding = [...world.history.realms].sort(
      (a, b) => a.foundedYear - b.foundedYear,
    );
    for (const realm of realmsByFounding) {
      const house = world.lore.houses.find((x) => x.realmId === realm.id);
      if (!house) continue;
      lines.push(`### House ${house.name} — realm of ${realm.name}`);
      lines.push("");
      const line = world.lore.rulers
        .filter((x) => x.realmId === realm.id)
        .sort((a, b) => a.startYear - b.startYear);
      for (const ruler of line) {
        lines.push(`- **${ruler.startYear}–${ruler.endYear}** ${ruler.name}`);
      }
      lines.push("");
    }
  }

  // Notable figures
  if (world.lore.figures.length) {
    lines.push("## Notable figures");
    lines.push("");
    for (const f of world.lore.figures) {
      lines.push(`- **${f.name}** — ${f.description}`);
    }
    lines.push("");
  }

  // Settlements
  lines.push("## Settlements");
  lines.push("");
  const tiers: Array<["city" | "town" | "village", string]> = [
    ["city", "Cities"],
    ["town", "Towns"],
    ["village", "Villages"],
  ];
  for (const [tier, heading] of tiers) {
    const list = world.settlements.settlements.filter((s) => s.tier === tier);
    if (!list.length) continue;
    lines.push(`### ${heading}`);
    lines.push("");
    for (const s of list) {
      const eco = world.economy.economies.find((e) => e.settlementId === s.id);
      const tags = [
        s.isCapital ? "**capital**" : "",
        s.isPort ? "port" : "",
        eco?.isTradeHub ? "trade hub" : "",
        eco ? eco.tier : "",
      ]
        .filter(Boolean)
        .join(", ");
      const goods = eco && eco.produces.length
        ? ` — ${eco.produces.map((k) => RESOURCE_NAMES[k]).join(", ")}`
        : "";
      lines.push(`- ${s.name}${tags ? ` (${tags})` : ""}${goods}`);
    }
    lines.push("");
  }

  // Faiths
  if (world.religion.faiths.length) {
    lines.push("## Faiths");
    lines.push("");
    for (const f of world.religion.faiths) {
      lines.push(
        `### ${f.name} — ${f.deity.name}, god of ${f.deity.domain}`,
      );
      lines.push("");
      lines.push(`> ${f.myth}`);
      lines.push("");
      lines.push(`Followed across ${f.followerRegions.length} region(s).`);
      lines.push("");
    }
  }

  // Resources & trade
  lines.push("## Resources & trade");
  lines.push("");
  if (m.majorExports) lines.push(`- **Major exports:** ${m.majorExports}`);
  const richestTown = world.settlements.settlements.find(
    (s) => s.id === world.economy.richest,
  );
  if (richestTown) lines.push(`- **Wealthiest settlement:** ${richestTown.name}`);
  const hubs = world.economy.economies
    .filter((e) => e.isTradeHub)
    .map((e) => world.settlements.settlements.find((s) => s.id === e.settlementId)?.name)
    .filter(Boolean);
  if (hubs.length) lines.push(`- **Trade hubs:** ${hubs.join(", ")}`);
  const depCounts = Object.entries(world.resources.counts)
    .filter(([, c]) => (c as number) > 0)
    .map(([k, c]) => `${RESOURCE_NAMES[Number(k)]} ×${c}`);
  if (depCounts.length) lines.push(`- **Deposits:** ${depCounts.join(", ")}`);
  lines.push("");

  // Chronicle
  lines.push("## Chronicle");
  lines.push("");
  for (const e of h.events) {
    lines.push(`- **${e.year} ${h.epoch}** — ${e.text}`);
  }
  lines.push("");

  lines.push("---");
  lines.push("");
  lines.push(
    `*Elevation fingerprint \`${m.contentHash}\`. This document and every map of ` +
      `${worldName} are pure functions of the seed — reproducible anywhere, forever.*`,
  );
  lines.push("");

  return lines.join("\n");
}
